name: Update Test Branch

on:
  push:
    branches: [master]
    
permissions: 
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "niuliangtao@gmail.com"

      - name: Update Test Branch
        run: |
          git checkout master
          git fetch origin
          git checkout master
          git pull
          #git tag -d $(git tag -l) || true
          #git fetch
          #git push origin --delete $(git tag -l)
          #git tag -d $(git tag -l) || true
          git checkout --orphan latest_branch
          git add -A
          git commit -am "clear history"
          git branch -D master
          git branch -m master
          git push -f origin master
          git push --set-upstream origin master
